language: python
git:
  depth: 2
python:
  # - "2.7"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install tox
  - pip install flake8
script:
  - flake8
  - tox
after_success:
    - pip install pytest pytest-cov requests requests-mock
    - pytest --cov=airtable
    - pip install codecov
    - codecov -t "be693bf3-8461-44e7-b372-0f01b0ac9360"
