language: python
git:
  depth: 2
python:
  # - "2.7"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  - "3.7"
branches:
  only:
  - master
  - dev/main
install:
  - pip install .
  - pip install tox
  - pip install flake8
script:
  - flake8
  - tox
after_success:
    - pip install codecov
    - codecov
