language: python
git:
  depth: 2
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
branches:
  only:
  - master
  - dev/main
script:
  - tox
install:
  - pip install .
  - pip install codecov
after_success:
    - codecov
