__version__ = "0.15.1"
__name__ = "airpandas"
__description__ = "Pandas interoperable version of airtable-python-wrapper"
__url__ = "https://github.com/ANaka/airpandas"
__author__ = "Alex Naka"
__authoremail__ = "alex.naka@gmail.com"
__license__ = "BSD-3"
__copyright__ = "Copyright 2020"
